"""Initial migration.

Revision ID: adc471319d7b
Revises: 
Create Date: 2024-06-02 23:51:12.824854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc471319d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_data')
    # ### end Alembic commands ###
